package ru.sosgps.wayrecall.odsmosrutelemetry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-02T18:39:47.279+04:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://webservice.telemetry.udo.fors.ru/", name = "TelemetryService")
@XmlSeeAlso({ObjectFactory.class})
public interface TelemetryService {

    /**
     * Сохранение массива данных по передвижению техники с показаниями датчиков
     */
    @RequestWrapper(localName = "storeTelemetryList", targetNamespace = "http://webservice.telemetry.udo.fors.ru/", className = "ru.sosgps.wayrecall.odsmosrutelemetry.StoreTelemetryList")
    @WebMethod
    @ResponseWrapper(localName = "storeTelemetryListResponse", targetNamespace = "http://webservice.telemetry.udo.fors.ru/", className = "ru.sosgps.wayrecall.odsmosrutelemetry.StoreTelemetryListResponse")
    public void storeTelemetryList(
        @WebParam(name = "telemetryWithDetails", targetNamespace = "")
        java.util.List<ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryWithDetails> telemetryWithDetails
    ) throws TelemetryException_Exception;

    /**
     * Тестовая операция - возвращает сумму двух входных целочисленных параметров
     */
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "testService", targetNamespace = "http://webservice.telemetry.udo.fors.ru/", className = "ru.sosgps.wayrecall.odsmosrutelemetry.TestService")
    @WebMethod
    @ResponseWrapper(localName = "testServiceResponse", targetNamespace = "http://webservice.telemetry.udo.fors.ru/", className = "ru.sosgps.wayrecall.odsmosrutelemetry.TestServiceResponse")
    public java.lang.Integer testService(
        @WebParam(name = "a", targetNamespace = "")
        java.lang.Integer a,
        @WebParam(name = "b", targetNamespace = "")
        java.lang.Integer b
    ) throws TelemetryException_Exception;

    /**
     * Сохранение данных по передвижению техники и значений показаний датчиков
     */
    @RequestWrapper(localName = "storeTelemetry", targetNamespace = "http://webservice.telemetry.udo.fors.ru/", className = "ru.sosgps.wayrecall.odsmosrutelemetry.StoreTelemetry")
    @WebMethod
    @ResponseWrapper(localName = "storeTelemetryResponse", targetNamespace = "http://webservice.telemetry.udo.fors.ru/", className = "ru.sosgps.wayrecall.odsmosrutelemetry.StoreTelemetryResponse")
    public void storeTelemetry(
        @WebParam(name = "telemetry", targetNamespace = "")
        ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryBa telemetry,
        @WebParam(name = "telemetryDetails", targetNamespace = "")
        java.util.List<ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryDetailBa> telemetryDetails
    ) throws TelemetryException_Exception;
}
