package ru.sosgps.wayrecall.odsmosrutelemetry;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-02T18:39:47.287+04:00
 * Generated source version: 2.7.3
 *
 */
@WebServiceClient(name = "TelemetryService", 
                  wsdlLocation = "http://ods.mos.ru/telemetry/telemetryWebService?wsdl",
                  targetNamespace = "http://webservice.telemetry.udo.fors.ru/") 
public class TelemetryService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.telemetry.udo.fors.ru/", "TelemetryService");
    public final static QName TelemetryServiceImplPort = new QName("http://webservice.telemetry.udo.fors.ru/", "KafkaProducerTelemetryServicePort");
    static {
        URL url = TelemetryService_Service.class.getResource("telemetryWebService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TelemetryService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "telemetryWebService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public TelemetryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TelemetryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TelemetryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TelemetryService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TelemetryService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TelemetryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TelemetryService
     */
    @WebEndpoint(name = "TelemetryServiceImplPort")
    public TelemetryService getTelemetryServiceImplPort() {
        return super.getPort(TelemetryServiceImplPort, TelemetryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TelemetryService
     */
    @WebEndpoint(name = "TelemetryServiceImplPort")
    public TelemetryService getTelemetryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TelemetryServiceImplPort, TelemetryService.class, features);
    }

}
