
package ru.sosgps.wayrecall.odsmosrutelemetry;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-02T18:39:47.271+04:00
 * Generated source version: 2.7.3
 */

@WebFault(name = "TelemetryException", targetNamespace = "http://webservice.telemetry.udo.fors.ru/")
public class TelemetryException_Exception extends Exception {
    
    private ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryException telemetryException;

    public TelemetryException_Exception() {
        super();
    }
    
    public TelemetryException_Exception(String message) {
        super(message);
    }
    
    public TelemetryException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TelemetryException_Exception(String message, ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryException telemetryException) {
        super(message);
        this.telemetryException = telemetryException;
    }

    public TelemetryException_Exception(String message, ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryException telemetryException, Throwable cause) {
        super(message, cause);
        this.telemetryException = telemetryException;
    }

    public ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryException getFaultInfo() {
        return this.telemetryException;
    }
}
