
package ru.sosgps.wayrecall.odsmosrutelemetry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.ws.security.WSConstants;
import org.apache.ws.security.WSPasswordCallback;
import org.apache.ws.security.handler.WSHandlerConstants;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.security.auth.callback.Callback;
import javax.security.auth.callback.CallbackHandler;
import javax.security.auth.callback.UnsupportedCallbackException;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-02T18:39:47.226+04:00
 * Generated source version: 2.7.3
 * 
 */

public final class TelemetryService_TelemetryServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.telemetry.udo.fors.ru/", "TelemetryService");

    private TelemetryService_TelemetryServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TelemetryService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TelemetryService_Service ss = new TelemetryService_Service(wsdlURL, SERVICE_NAME);
        TelemetryService port = ss.getTelemetryServiceImplPort();

        Map ctx = ((BindingProvider)port).getRequestContext();
        ctx.put("ws-security.username", "KSBSTELS");
        //ctx.put("ws-security.callback-handler", ClientPasswordCallback.class.getName());
        // instead of above line can also do:
        ctx.put("ws-security.password", "KSBSTELS");

        {
        System.out.println("Invoking storeTelemetryList...");
        java.util.List<ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryWithDetails> _storeTelemetryList_telemetryWithDetails = null;
        try {
            port.storeTelemetryList(_storeTelemetryList_telemetryWithDetails);

        } catch (TelemetryException_Exception e) { 
            System.out.println("Expected exception: TelemetryException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking testService...");
        java.lang.Integer _testService_a = null;
        java.lang.Integer _testService_b = null;
        try {
            java.lang.Integer _testService__return = port.testService(_testService_a, _testService_b);
            System.out.println("testService.result=" + _testService__return);

        } catch (TelemetryException_Exception e) { 
            System.out.println("Expected exception: TelemetryException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking storeTelemetry...");
        ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryBa _storeTelemetry_telemetry = new ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryBa();
        java.util.List<ru.sosgps.wayrecall.odsmosrutelemetry.TelemetryDetailBa> _storeTelemetry_telemetryDetails = null;
        try {
            port.storeTelemetry(_storeTelemetry_telemetry, _storeTelemetry_telemetryDetails);

        } catch (TelemetryException_Exception e) { 
            System.out.println("Expected exception: TelemetryException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
