
package ru.sosgps.wayrecall.odsmosrutelemetry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-02T18:39:47.226+04:00
 * Generated source version: 2.7.3
 * 
 */

public final class TelemetryService_TelemetryServiceImplPort_Client2 {

    private static final QName SERVICE_NAME = new QName("http://webservice.telemetry.udo.fors.ru/", "TelemetryService");

    private TelemetryService_TelemetryServiceImplPort_Client2() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TelemetryService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TelemetryService_Service ss = new TelemetryService_Service(wsdlURL, SERVICE_NAME);
        TelemetryService port = ss.getTelemetryServiceImplPort();

        Map ctx = ((BindingProvider)port).getRequestContext();
        ctx.put("ws-security.username", "KSBSTELS");
        //ctx.put("ws-security.callback-handler", ClientPasswordCallback.class.getName());
        // instead of above line can also do:
        ctx.put("ws-security.password", "KSBSTELS");


        Integer sum = port.testService(5, 6);

        System.out.println("sum="+sum);


    }

}
